environments:
  default:
    values:
    - environments/default/operator.yaml
    - environments/default/stack.yaml
  production:
    values:
    - environments/production/operator.yaml
    - environments/production/stack.yaml
---
repositories:
  - name: elastic
    url: https://helm.elastic.co 

commonLabels:
  release: run-team-elasticsearch

releases:
  - name: operator
    namespace: elastic-system
    createNamespace: true
    chart: elastic/eck-operator
    version: ~2.13.0
    values:
    - values/operator.yaml

  - name: stack
    needs:
    - elastic-system/operator
    namespace: elastic-stack
    createNamespace: true
    chart: elastic/eck-stack
    version: ~0.11.0
    values:
    - values/stack.yaml
