eck-elasticsearch:
  version: 8.16.0-SNAPSHOT
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: monitoring
          namespace: observability
    logs:
      elasticsearchRefs:
        - name: monitoring
          namespace: observability
  podDisruptionBudget:
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: eck-stack
    disabled: false
  nodeSets:
    - name: main
      count: 3
      config:
        node.roles:
          - master
        node.store.allow_mmap: false
      podTemplate:
        spec: 
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 8Gi
                  cpu: 2
              securityContext:
                readOnlyRootFilesystem: false
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: eck-stack
                  topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - eu-west-1-a
                        - eu-west-1-b
                        - eu-west-1-c
        initContainers:
          - command:
              - sh
              - '-c'
              - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
          - command:
              - sh
              - '-c'
              - >-
                bin/elasticsearch-plugin remove --purge analysis-icu ;
                bin/elasticsearch-plugin install --batch analysis-icu
            name: install-plugins
            securityContext:
              privileged: true
        priorityClassName: ''
    - name: data
      count: 6
      config:
        node.roles:
          - data
          - ingest
          - ml
          - transform
        node.store.allow_mmap: false
      podTemplate:
        spec: 
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 16Gi
                  cpu: 4
              securityContext:
                readOnlyRootFilesystem: false
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: eck-stack
                  topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.kubernetes.io/zone
                      operator: In
                      values:
                        - eu-west-1-a
                        - eu-west-1-b
                        - eu-west-1-c
        initContainers:
          - command:
              - sh
              - '-c'
              - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
          - command:
              - sh
              - '-c'
              - >-
                bin/elasticsearch-plugin remove --purge analysis-icu ;
                bin/elasticsearch-plugin install --batch analysis-icu
            name: install-plugins
            securityContext:
              privileged: true
        priorityClassName: ''

eck-kibana:
  spec:
    count: 2
